# Generated by Django 4.2.1 on 2023-07-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_customer_id',
            new_name='paypal_customer_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_card_last4',
            new_name='paypal_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_payment_method_id',
            new_name='paypal_payment_method_id',
        ),
    ]
