# Generated by Django 4.2.1 on 2023-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_stripe_customer_id_customer_paypal_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='pickuped_at',
            new_name='pickedup_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='paypal_email',
            field=models.EmailField(max_length=255),
        ),
    ]
