# Generated by Django 4.2.1 on 2023-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='paypal_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
