# Generated by Django 4.2.1 on 2023-07-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customer_paypal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='paypal_email',
        ),
    ]
