# Generated by Django 4.2.1 on 2023-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customer_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
