# Generated by Django 4.2.1 on 2023-07-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_courier_lat_courier_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
    ]
