# Generated by Django 4.2.1 on 2023-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transaction_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='courier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
