"""
Django settings for drivex project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b3xoe-@_&50f5a9v0t=8!e84g=miygz4ylo@z!lfisodc@sk-='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'social_django',
    'bootstrap4',
    'core.apps.CoreConfig',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
    'core.middleware.ProfileMiddleware'
]

ROOT_URLCONF = 'drivex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'social_django.context_processors.backends',
                # 'social_django.context_processors.login_redirect',
                # 'drivex.context_processors.export_vars',
            ],
        },
    },
]

WSGI_APPLICATION = 'drivex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':  'drivex',
        'USER': 'postgres',
        'PASSWORD': 'victor100',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/sign-in'
LOGIN_REDIRECT_URL = '/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AUTHENTICATION_BACKENDS = (
    # 'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = "544745680203048"
SOCIAL_AUTH_FACEBOOK_SECRET = "f93bc07943543fb03d83860a90807eac"
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email'
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'victorodongo397@gmail.com'
EMAIL_HOST_PASSWORD = 'rzgjaexdpluyorgs'
DEFAULT_FROM_EMAIL = 'Drive Express <no-reply@drivex.localhost>'

# FIREBASE_ADMIN_CREDENTIAL = os.path.join(
#     BASE_DIR, "drivex-df78b-firebase-adminsdk-oi4ak-4f0c4257ec.json")

STRIPE_API_PUBLIC_KEY = "pk_test_51NObcfEcaEZGo6pJMMluaGFLWCJGnkbwFfegQ5OY26n2blAIj45htwpz87ZA3J4ARPaH7hJmRJtpn7fEfLWOZ3UR00i7Dret6e"
STRIPE_API_SECRET_KEY = "sk_test_51NObcfEcaEZGo6pJH0In2Nx0LbVwRMBsbR9rebSKuhYOH7FVkPf9E9UGSz4cQiPvjtmZVHpDAnLAyJTjlF77OcUc00tmuvt7I5"

GOOGLE_API_KEY = 'AIzaSyAAPf-PH9qBF_HugsrYjn_lXTJlFvhE0Wk'

# PayPal settings
PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = 'AViXy3AqztngAJ-O7ggs8DYMgvXwSvGWYCyVnPcdBt6L821iWKKlrLPZdLBDe1UyrAAlgeW_mvKZMTIB'
PAYPAL_SECRET_KEY = 'ENT8ig3CW2x2eZAZcNa3t9JKbrzss9LuBAs2QoqeSHuRO4AZ-w21cCzQ4v4Wy8npK0l9LQKgjWf4oKWF'


# PayPal SDK settings

# PAYPAL_SDK_CONFIG = {
#     "mode": PAYPAL_MODE,
#     "client_id": PAYPAL_CLIENT_ID,
#     "client_secret": PAYPAL_SECRET_KEY,
# }

# Django PayPal settings

DJANGO_PAYPAL_SETTINGS = {
    "mode": PAYPAL_MODE,
    "client_id": PAYPAL_CLIENT_ID,
    "client_secret": PAYPAL_SECRET_KEY,
}

# Add the Django PayPal settings to the main Django settings

PAYPAL_SETTINGS = {
    "urls": {
        "sandbox": "https://www.sandbox.paypal.com/checkoutnow",
        "live": "https://www.paypal.com/checkoutnow",
    },
    "settings": DJANGO_PAYPAL_SETTINGS,
}
PAYPAL_URLS = PAYPAL_SETTINGS["urls"]

# Update the main Django settings with the PayPal settings

# settings.PAYPAL = PAYPAL_SETTINGS

# NGROK_URL = os.environ['NGROK_URL']

ASGI_APPLICATION = "drivex.asgi.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# JAZZMIN SETTINGS
JAZZMIN_SETTINGS = {
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "DriveX Admin",
    
     # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Library Admin",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to DriveX Admin",
    
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,
    
     # Copyright on the footer
    "copyright": "DriveX Ltd",

}


JAZZMIN_UI_TWEAKS = {
    "theme": "simplex",
}

# INTASEND_SECTRET_KEY = "ISSecretKey_live_0526687a-d69f-4321-88e5-1ad98eaffa10"
# INTASEND_PUBKEY = "ISPubKey_live_9eae6ea6-c221-4ab3-8805-933aea7aca63"

